substitutions:
  name: xiaomi-philips-zhirui
  friendly_name: "Xiaomi Philips Zhirui"
  device_description: "Xiaomi Philips Zhirui Smart LED Ball Lamp (Model: 9290012800)"
  project_version: "1.0.0"

esphome:
  name: ${name}
  name_add_mac_suffix: true
  friendly_name: ${friendly_name}
  comment: ${device_description}
  min_version: 2024.6.0
  project:
    name: "wernerhp.esphome-xiaomi-philips-zhirui"
    version: ${project_version}
  on_boot:
    - priority: 600
      then:
        - lambda: |-
            id(boot_counter) += 1;
        - select.set_index:
            id: power_mode
            index: !lambda 'return id(restore_mode);'
        - lambda: |-
            int mode = id(restore_mode);
            switch(mode) {
              case 0:  // Always Off
                id(bulb).turn_off();
                break;
              case 1:  // Always On
                id(bulb).turn_on();
                break;
              case 2:  // Restore Previous State
                // No action needed - restore_mode handles it
                break;
              default:
                id(bulb).turn_off();
                break;
            }

esp8266:
  board: esp_wroom_02

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    password: !secret fallback_password

ota:
  platform: esphome

preferences:
    flash_write_interval: 5min

logger:
  level: INFO

api:

captive_portal:

web_server:
  port: 80
  version: 3

globals:
  - id: restore_mode
    type: int
    restore_value: yes
    initial_value: "2"  # 0 = Always Off, 1 = Always On, 2 = Restore Previous State
  
  - id: boot_counter
    type: int
    restore_value: yes
    initial_value: "0"

light:
  - platform: color_temperature
    id: bulb
    name: "Bulb"
    color_temperature: output_color_temperature
    brightness: output_brightness
    cold_white_color_temperature: 5700 K
    warm_white_color_temperature: 3000 K
    gamma_correct: 0
    default_transition_length: 350ms
    restore_mode: RESTORE_AND_OFF

output:
  - platform: esp8266_pwm
    pin: GPIO12
    id: output_color_temperature
    inverted: true
  - platform: esp8266_pwm
    pin: GPIO15
    id: output_brightness
    min_power: 0.06
    zero_means_zero: true

sensor:
  - platform: ntc
    name: "NTC Temperature"
    id: bulb_temp
    sensor: resistance0
    calibration:
      b_constant: 3950
      reference_temperature: 25°C
      reference_resistance: 100000
    on_value_range:
      # Throttle brightness when getting warm
      - above: 60.0
        below: 64.9
        then:
          - light.control:
              id: bulb
              brightness: 40%
          - logger.log: "Thermal Throttling: Brightness capped at 40%"
      
      # Emergency shutoff
      - above: 65.0
        then:
          - light.turn_off: bulb
          - logger.log: "EMERGENCY SHUTDOWN: Temperature critical!"

  - platform: resistance
    id: resistance0
    internal: true
    sensor: adc0
    configuration: DOWNSTREAM
    resistor: 500000
    reference_voltage: 3.3

  - platform: adc
    id: adc0
    internal: true
    pin: A0
    update_interval: 60s
    filters:
      - median:
          window_size: 3
          send_every: 1
          send_first_at: 1

  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
    entity_category: diagnostic

  - platform: template
    name: "Boot Counter"
    id: boot_counter_sensor
    accuracy_decimals: 0
    state_class: total_increasing
    entity_category: diagnostic
    icon: "mdi:restart"
    lambda: |-
      return id(boot_counter);


text_sensor:
  - platform: template
    name: "Firmware Version"
    icon: "mdi:label-outline"
    entity_category: diagnostic
    lambda: |-
      return {"${project_version}"};
    update_interval: 24h

  - platform: version
    name: "ESPHome Version"
    hide_timestamp: true
  
  - platform: template
    name: "Last Boot Reason"
    icon: "mdi:information-outline"
    entity_category: diagnostic
    lambda: |-
      return {system_get_rst_info()->reason == 0 ? "Power On" :
              system_get_rst_info()->reason == 1 ? "Hardware Watchdog" :
              system_get_rst_info()->reason == 2 ? "Software Watchdog" :
              system_get_rst_info()->reason == 3 ? "Software Reset" :
              system_get_rst_info()->reason == 4 ? "Deep Sleep" :
              system_get_rst_info()->reason == 5 ? "Hardware Reset" :
              system_get_rst_info()->reason == 6 ? "Software Restart" : "Unknown"};
    update_interval: never

  - platform: wifi_info
    mac_address:
      name: "Mac Address"
      icon: mdi:wifi
      disabled_by_default: true
    ip_address:
      name: "IP Address"
      icon: mdi:wifi
      disabled_by_default: true
    ssid:
      name: "SSID"
      icon: mdi:wifi-strength-2
      disabled_by_default: true

select:
  - platform: template
    name: "Power On State"
    id: "power_mode"
    optimistic: true
    icon: mdi:electric-switch
    initial_option: "Restore Previous State"  # Matches restore_mode: 2
    options:
      - "Always Off"              # index 0 → restore_mode 0
      - "Always On"               # index 1 → restore_mode 1
      - "Restore Previous State"  # index 2 → restore_mode 2
    on_value:
      then:
        - lambda: |-
            auto idx = id(power_mode).active_index();
            if (idx.has_value()) {
              id(restore_mode) = idx.value();
            }

button:
  - platform: factory_reset
    name: "Factory Reset"
    id: factory_reset_btn
    entity_category: config
    icon: mdi:restart-alert
  
  - platform: restart
    name: "Restart"
    id: restart_btn
    entity_category: config
    icon: mdi:restart
  
  - platform: template
    name: "Night Mode"
    id: night_mode_btn
    icon: mdi:weather-night
    on_press:
      then:
        - light.turn_on:
            id: bulb
            brightness: 10%
            color_temperature: 3000K
            transition_length: 350ms
      
# Enable time component to reset energy at midnight
time:
  - platform: homeassistant
    id: homeassistant_time

