substitutions:
  name: "bneta"
  friendly_name: "BNETA Smart Plug"
  comment: "The BNETA Smart Plug is an energy monitoring, scheduling and control plug with load management and automation capability."
  project_name: "wernerhp.bneta"
  project_version: "0.2.5"

  button_1_pin: P24
  relay_1_pin: P26
  led_pin: P8
  rx_pin: P10
  tx_pin: P11

dashboard_import:
  package_import_url: github://wernerhp/esphome/bneta-smart-plug/bneta.yaml

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true

  project:
    name: ${project_name}
    version: ${project_version}

bk72xx:
  board: cb2s
  framework:
    version: recommended

# Enable logging
logger:
  level: WARN

# Enable Home Assistant API
api:

ota:
  platform: esphome

safe_mode:
  disabled: false
  reboot_timeout: 10min
  num_attempts: 5

wifi:
  # Enable fallback hotspot in case wifi connection fails
  ap:
    password: "12345678"

captive_portal:

web_server:
  port: 80

output:
  - platform: gpio
    pin: ${relay_1_pin}
    id: relay_1

switch:
  - platform: output
    id: switch_1
    output: relay_1
    name: "Relay"
    restore_mode: RESTORE_DEFAULT_OFF

binary_sensor:
  - platform: gpio
    pin: ${button_1_pin}
    name: "Button"
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_press:
      - switch.toggle: switch_1
    internal: true

button:
  - platform: restart
    name: "Restart"

status_led:
  pin:
    number: ${led_pin}
    inverted: true

uart:
  id: uart_bus
  tx_pin: ${tx_pin}
  rx_pin: ${rx_pin}
  baud_rate: 4800
  stop_bits: 1

sensor:
  - platform: bl0942
    uart_id: uart_bus
    voltage:
      name: "Voltage"
      accuracy_decimals: 1
    current:
      name: "Current"
      accuracy_decimals: 2
    power:
      name: "Power"
      accuracy_decimals: 0
      id: power
    energy:
      name: "Energy"
      accuracy_decimals: 2
    frequency:
      name: "Frequency"
      accuracy_decimals: 2
    update_interval: 1s

  - platform: total_daily_energy
    name: 'Total Daily Energy'
    accuracy_decimals: 2
    power_id: power

  - platform: uptime
    name: "Uptime"

  - platform: wifi_signal
    name: "WiFi Signal"

text_sensor:
  - platform: template
    name: "Firmware version"
    icon: "mdi:label-outline"
    entity_category: diagnostic
    lambda: |-
      return {"${project_version}"};
    update_interval: 6h

  - platform: version
    name: "ESPHome Version"

  - platform: wifi_info
    mac_address:
      name: "Mac Address"
      icon: mdi:wifi
    ip_address:
      name: "IP Address"
      icon: mdi:wifi
    ssid:
      name: "SSID"
      icon: mdi:wifi-strength-2
    bssid:
      name: "BSSID"
      icon: mdi:wifi-strength-2

# Enable time component to reset energy at midnight
time:
  - platform: homeassistant
    id: homeassistant_time