substitutions:
  name: "centurion-d5-evo"
  friendly_name: "Centurion D5 Evo"
  comment: "Control your Centurion D5 Evo gate motor remotely."
  project_name: "wernerhp.esphome_centurion_d5_evo"
  project_version: "2.0.0"
  name_add_mac_suffix: true

  relay_1_pin: GPIO32
  relay_2_pin: GPIO33
  relay_3_pin: GPIO25
  relay_4_pin: GPIO26
  led_pin: GPIO23

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  comment: ${comment}
  name_add_mac_suffix: ${name_add_mac_suffix}
  
  project:
    name: ${project_name}
    version: ${project_version}

  on_boot:
    priority: -100  # Run after all sensors are initialized
    then:
      - lambda: |-
          // Set initial gate state based on LED
          if (id(status_led).state) {
            id(status).publish_state("Open");
            id(gate).position = cover::COVER_OPEN;
          } else {
            id(status).publish_state("Closed");
            id(gate).position = cover::COVER_CLOSED;
          }
          id(gate).current_operation = CoverOperation::COVER_OPERATION_IDLE;
          id(gate).publish_state();

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:

ota:
  - platform: esphome
    password: !secret ota_password
  - platform: http_request

safe_mode:
  reboot_timeout: 10min
  num_attempts: 5

update:
  - platform: http_request
    name: "Firmware Update"
    source: https://github.com/wernerhp/esphome/releases/latest/download/centurion-d5-evo-ota.bin
    update_interval: 6h

dashboard_import:
  package_import_url: github://wernerhp/esphome/centurion-d5-evo/centurion-d5-evo.yaml@main
  import_full_config: false

# Fallback OTA via HTTP (backup method)
http_request:
  verify_ssl: false
  timeout: 10s

wifi:
  power_save_mode: NONE

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    password: d5evo12345
  
improv_serial:

captive_portal:

web_server:
  version: 3

binary_sensor:
  - platform: gpio
    pin: ${led_pin}
    id: status_led
    name: "Status LED"
    entity_category: diagnostic
    icon: mdi:led-outline
    disabled_by_default: true
    # publish_initial_state: true
    trigger_on_initial_state: true
    filters:
        delayed_on_off: 100ms
    # Blink codes:
    #   Off = Gate is closed
    #   On = Gate is partially or fully open
    #   Continuous slow flash = Gate is opening
    #   Continuous fast flash = Gate is closing
    #   1 flash / 2 sec = Pillar light override activated
    #   2 flashes / 2 sec = No mains present
    #   3 flashes / 2 sec = Battery voltage is low
    on_multi_click:
      - timing: # Off = Closed
          - OFF for at least 2000ms
        then:
          - logger.log: "Closed"
          - text_sensor.template.publish:
              id: status
              state: "Closed"
          - lambda: |-
              id(gate).position = cover::COVER_CLOSED;
              id(gate).current_operation = CoverOperation::COVER_OPERATION_IDLE;
              id(gate).publish_state();
        invalid_cooldown: 0ms

      - timing: # On = Partially or fully open
          - ON for at least 1000ms
        then:
          - logger.log: "Open"
          - text_sensor.template.publish:
              id: status
              state: "Open"
          - lambda: |-
              id(gate).position = cover::COVER_OPEN;
              id(gate).current_operation = CoverOperation::COVER_OPERATION_IDLE;
              id(gate).publish_state();
        invalid_cooldown: 0ms

      - timing: # Continuous fast flash = Closing
          - ON for 125ms to 175ms
          - OFF for 125ms to 175ms
        then:
          - logger.log: "Closing"
          - text_sensor.template.publish:
              id: status
              state: "Closing"
          - lambda: |-
              id(gate).current_operation = CoverOperation::COVER_OPERATION_CLOSING;
              id(gate).publish_state();
        invalid_cooldown: 0ms

      - timing: # Continuous slow flash = Opening (~300ms cycle)
          - ON for 275ms to 400ms
          - OFF for 275ms to 400ms
        then:
          - logger.log: "Opening"
          - text_sensor.template.publish:
              id: status
              state: "Opening"
          - lambda: |-
              id(gate).current_operation = CoverOperation::COVER_OPERATION_OPENING;
              id(gate).publish_state();
        invalid_cooldown: 0ms

      - timing: # 1 flash / 2 sec = Pillar light override
          - ON for 150ms to 275ms
          - OFF for 1700ms to 1900ms
        then:
          - logger.log: "Pillar light override"
          - text_sensor.template.publish:
              id: status
              state: "Pillar light override"
        invalid_cooldown: 100ms

      - timing: # 2 flashes / 2 sec = No mains
          - ON for 150ms to 275ms
          - OFF for 150ms to 275ms
          - ON for 150ms to 275ms
          - OFF for 1100ms to 1500ms
        then:
          - logger.log: "No Mains"
          - text_sensor.template.publish:
              id: status
              state: "No Mains"
        invalid_cooldown: 100ms

      - timing: # 3 flashes / 2 sec = Battery low
          - ON for 150ms to 275ms
          - OFF for 150ms to 275ms
          - ON for 150ms to 275ms
          - OFF for 150ms to 275ms
          - ON for 150ms to 275ms
          - OFF for 400ms to 1100ms
        then:
          - logger.log: "Low Battery"
          - text_sensor.template.publish:
              id: status
              state: "Low Battery"
        invalid_cooldown: 100ms


output:
  - platform: gpio
    pin: ${relay_1_pin}
    id: relay_1
  - platform: gpio
    pin: ${relay_2_pin}
    id: relay_2
  - platform: gpio
    pin: ${relay_3_pin}
    id: relay_3

button:
  - platform: output
    output: relay_1
    id: button_1
    disabled_by_default: true
    duration: 1000ms
    name: "Open / Auto Close"
    icon: "mdi:gate"
  - platform: output
    output: relay_2
    id: button_2
    disabled_by_default: true
    duration: 3000ms # Autoclose override time
    name: "Open / Manual Close"
    icon: "mdi:gate-alert"
  - platform: output
    output: relay_3
    id: button_3
    duration: 1000ms
    name: "Pedestrian"
    icon: "mdi:walk"

switch:
  - platform: gpio
    pin: ${relay_4_pin}
    id: lock_relay
    internal: true
    restore_mode: RESTORE_DEFAULT_OFF  # Remember state, default to unlocked

lock:
  - platform: template
    name: "Lock"
    id: gate_lock
    lambda: |-
      if (id(lock_relay).state) {
        return LOCK_STATE_LOCKED;
      } else {
        return LOCK_STATE_UNLOCKED;
      }
    lock_action:
      - switch.turn_on: lock_relay
    unlock_action:
      - switch.turn_off: lock_relay

cover:
  - platform: template
    name: "Gate"
    device_class: gate
    id: gate
    open_action:
      - button.press: button_1
    close_action:
      - button.press: button_1
    stop_action:
      - button.press: button_1
    optimistic: false

# # Sensors for ESP version and WIFI information
text_sensor:
  - platform: template
    icon: mdi:gate
    id: status
    name: "Status"
  # Installed version
  - platform: template
    name: "Device Version"
    id: device_version
    icon: "mdi:tag"
    entity_category: diagnostic
    lambda: |-
      return {"${project_version}"};
    update_interval: 6h
  # ESPHome version
  - platform: version
    hide_timestamp: true
    name: 'ESPHome Version'
  # IP address and connected SSID
  - platform: wifi_info
    ip_address:
      name: 'IP Address'
      icon: mdi:ip-network
    ssid:
      name: 'SSID'
      icon: mdi:wifi

sensor:
  # Uptime
  - platform: uptime
    name: Uptime Sensor
    icon: mdi:timer-outline
  # WiFi signal
  - platform: wifi_signal
    name: "WiFi Signal"
    icon: mdi:wifi-strength-2
    update_interval: 120s

esp32_ble_tracker:
  scan_parameters:
    active: true

bluetooth_proxy:
  active: true