substitutions:
  # Default name
  name: "cbi-astute"
  # Default friendly name   
  friendly_name: "CBI Astute"
  # Description as appears in ESPHome & top of webserver page
  comment: "The base template for CBI Astute Smart devices."

  #Voltage Devider Starting Value
  voltage_divider: "1566"
  #current Resistor Starting Value
  current_resistor: "0.000994"
  #Currnt Multiplier Starting Value
  current_multiply: "0.878"
# Current Limit in Amps
  current_limit : "30"

  # Project Name
  project_name: "CBI.Astute"
  # Projection version denotes the release version of the yaml file, allowing checking of deployed vs latest version
  project_version: "v1.0.0"
  # Allows ESP device to be automatically linked to an 'Area' in Home Assistant. Typically used for areas such as 'Lounge Room', 'Kitchen' etc  
  room: ""
  # Appends the mac Address to the device name, set to "false" to disable
  name_add_mac_suffix: "true"
  # Restore the relay (GPO switch) upon reboot to state:
  relay_restore_mode: RESTORE_DEFAULT_ON
  # Set the update interval for sensors
  sensor_update_interval: 10s
  # Define a domain for this device to use. i.e. iot.home.lan (so device will appear as smartpad-em32-smart-plug.local in DNS/DHCP logs)
  dns_domain: ".local"
  # Set timezone of the smart plug. Useful if the plug is in a location different to the HA server. Can be entered in unix Country/Area format (i.e. "Africa/Johannesburg")
  timezone: "Africa/Johannesburg"
  # Set the duration between the sntp service polling ntp.org servers for an update
  sntp_update_interval: 6h
  # Network time servers for your region, enter from lowest to highest priority. To use local servers update as per zones or countries at: https://www.ntppool.org/zone/@
  sntp_server_1: "0.pool.ntp.org"
  sntp_server_2: "1.pool.ntp.org"
  sntp_server_3: "2.pool.ntp.org"  
  # Enables faster network connections, with last connected SSID being connected to and no full scan for SSID being undertaken
  wifi_fast_connect: "false"
  # Define logging level: NONE, ERROR, WARN, INFO, DEBUG (Default), VERBOSE, VERY_VERBOSE
  log_level: "INFO"
  # Hide the ENERGY sensor that shows kWh consumed, but with no time period associated with it. Resets when device restarted and reflashed.
  hide_energy_sensor: "true"
  # Enable or disable the use of IPv6 networking on the device
  ipv6_enable: "false"
  #Specify Web Server Versions
  web_server_version: "2"


########################## End of Substitutions #########################

dashboard_import:
  package_import_url: github://Smartpadza/Device_Configs/cbi-asc.yaml
  import_full_config: false # or true

globals:
  - id: restore_mode
    type: int
    restore_value: yes
    initial_value: "2"  # 0 = Always Off, 1 = Always On, 2 = Restore Previous State

  - id: total_energy
    type: float
    restore_value: yes
    initial_value: '0.0'

  - id: overload_count
    type: int
    restore_value: no
    initial_value: "0"

  # Add global variable for current_multiply
  - id: current_multiply
    type: float
    restore_value: yes
    initial_value: ${current_multiply}
    
#Board Configuration
rtl87xx:
  board: wr3e
  framework:
    version: recommended

#Core Configuration
esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  comment: "${comment}"
  area: "${room}"
  name_add_mac_suffix: "${name_add_mac_suffix}"
  min_version: 2024.6.0
  project:
    name: "${project_name}"
    version: "${project_version}"
    
  #Configuration to allow selection of Power restore Mode
  on_boot:
  - priority: 600
    then:
      - select.set_index:
          id: power_mode
          index: !lambda |-
                    return id(restore_mode);  // Index matches restore_mode (0, 1, 2)
      - lambda: |-
          int mode = id(restore_mode);
          switch(mode) {
            case 0:  // Always Off
              id(relay).turn_off();
              break;
            case 1:  // Always On
              id(relay).turn_on();
              break;
            case 2:  // Restore Previous State
              // No action needed; switch.restore_mode handles this
              break;
            default:
              id(relay).turn_off();  // Fallback to safe state
              break;
          }
          // Apply restored values to HLW8012 sensor
          id(power_sensor).set_voltage_divider(id(voltage_divider_number).state);
          id(power_sensor).set_current_resistor(id(current_resistor_number).state);
          id(power_sensor).setup();
select:
  - platform: template
    name: "Power On State"
    id: "power_mode"
    optimistic: true
    icon: mdi:electric-switch
    initial_option: "Restore Previous State"  # Matches restore_mode: 2
    options:
      - "Always Off"       # index 0 → restore_mode 0
      - "Always On"        # index 1 → restore_mode 1
      - "Restore Previous State"  # index 2 → restore_mode 2
    on_value:
      then:
        - lambda: |-
            id(restore_mode) = i;  

#prevent rapid changes to a component from being quickly written to the flash and wearing it out
preferences:
  flash_write_interval: 5min

#Enable Home Assistant API
api:
#Enable OTA Updates
ota:
  - platform: esphome
#Specify Logging level
logger:
  level: ${log_level}
  baud_rate: 0
#Allow MDNS to be disabled
mdns:
  disabled: false
#nable Web Server
web_server:
  port: 80
  version: ${web_server_version}

network:
  enable_ipv6: ${ipv6_enable}
#Wifi Configuration
wifi:
  # This spawns an AP with the device name and mac address with no password.
  ap: {}
  # Allow rapid re-connection to previously connect WiFi SSID, skipping scan of all SSID
  fast_connect: "${wifi_fast_connect}"
  # Define dns domain / suffix to add to hostname
  domain: "${dns_domain}"

#Enable Captive Portal Fallback
captive_portal:

#WiFi Configuration
#esp32_improv:
#  authorizer: relay_button
#  status_indicator: output_status_led

#Device LED Configurations
light:
  platform: status_led
  id: status
  output: output_status_led
output:

  #relay Status LED (Red)
  - platform: gpio
    pin:
      number: PA05
      inverted: true
    id: output_status_led

  #Device Status LED (Blue)
  - platform: gpio
    pin:
      number: PA23
      inverted: true
    id: gpio_output_relay_led

# Relay & Status LED Linking
switch:
  - platform: gpio
    pin: PA12
    id: relay
    name: "Switch"
    device_class: outlet
    restore_mode: ${relay_restore_mode}
    on_turn_on:
      - output.turn_on: gpio_output_relay_led  # Turn on the LED when the relay is active
    on_turn_off:
      - output.turn_off: gpio_output_relay_led  # Turn off the LED when the relay is inactive

#HLW8012 Power Monitoring Configuration and Calibration Configuration
number:
  - platform: template
    id: voltage_divider_number  # Add ID for reference
    name: "Voltage Divider"
    optimistic: true
    min_value: 1
    max_value: 4000
    step: 1
    unit_of_measurement: ohms
    initial_value: ${voltage_divider}
    restore_value: true
    entity_category: config
    disabled_by_default: true
    mode: box
    on_value:
      then:
        - lambda: |-
            id(power_sensor).set_voltage_divider(x);
            id(power_sensor).setup();

  - platform: template
    id: current_resistor_number  # Add ID for reference
    name: "Current Resistor"
    optimistic: true
    min_value: 0.0000
    max_value: 0.0100
    step: 0.0001
    unit_of_measurement: ohms
    initial_value: ${current_resistor}
    restore_value: true
    entity_category: config
    disabled_by_default: true
    mode: box
    on_value:
      then:
        - lambda: |-
            id(power_sensor).set_current_resistor(x);
            id(power_sensor).setup();

  # Add new number entity for current_multiply
  - platform: template
    name: "Current Multiplier"
    id: current_multiply_number
    optimistic: true
    min_value: 0.1
    max_value: 5.0
    step: 0.1
    initial_value: ${current_multiply}
    restore_value: true
    entity_category: config
    disabled_by_default: true
    mode: box
    on_value:
      then:
        - lambda: |-
            id(current_multiply) = x;

#Sensor Configurations
sensor:
  - platform: hlw8012
    id: power_sensor
    current_resistor: ${current_resistor}  # Initial value from substitution
    voltage_divider: ${voltage_divider}    # Initial value from substitution
    model: BL0937
    change_mode_every: 8
    cf_pin: PA15
    cf1_pin: PA14
    sel_pin:
      number: PA19
      inverted: true
    update_interval: 10s
    voltage:
      name: "Voltage"
      icon: mdi:sine-wave
      filters:
        - throttle_average: ${sensor_update_interval}
    current:
      name: "Current"
      id: current_id
      filters:
        - multiply: !lambda 'return id(current_multiply);' 
      on_value_range:
        - above: ${current_limit}
          then:
            - delay: 5s
            - switch.turn_off: relay
            - lambda: 'id(overload_count) += 1;'
    power:
      name: "Power"
      id: power_id
      icon: mdi:power
      filters:
        - throttle_average: ${sensor_update_interval}
        - lambda: if (x < 3.0) return 0.0; else return x;    #For the chip will report less than 3w power when no load is connected

    energy:
      name: "Energy"
      id: energy
      icon: mdi:lightning-bolt
      unit_of_measurement: kWh
      filters:
        - throttle: ${sensor_update_interval}
        # Multiplication factor from W to kW is 0.001
        - multiply: 0.001
 
  - platform: uptime
    name: "Uptime Sensor"
    id: uptime_sensor
    update_interval: 1h
    entity_category: diagnostic
    internal: true

  - platform: wifi_signal
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 1h
    entity_category: "diagnostic"
    disabled_by_default: true

  - platform: copy
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: |-
          return (x > -50) ? 100 : 
                 (x < -100) ? 0 : 
                 2 * (x + 100);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
    device_class: ""
 
# Added total energy persistence
  - platform: total_daily_energy
    name: "Total Energy"
    power_id: power_id
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
    icon: mdi:lightning-bolt-circle
    accuracy_decimals: 3
  
#Diagnostic Data Sesnors    
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
      icon: mdi:ip-network
      entity_category: diagnostic
    ssid:
      name: "Connected SSID"
      icon: mdi:wifi-strength-2
      entity_category: diagnostic
    mac_address:
      name: "Mac Address"
      icon: mdi:network-pos
      entity_category: diagnostic

  #  Creates a sensor showing when the device was last restarted
  - platform: template
    name: 'Last Restart'
    id: device_last_restart
    icon: mdi:clock
    entity_category: diagnostic
  #  Creates a sensor of the uptime of the device, in formatted days, hours, minutes and seconds
  - platform: template
    name: "Uptime"
    entity_category: diagnostic
    lambda: |-
      int seconds = static_cast<int>(id(uptime_sensor).state);
      int days = seconds / 86400;
      seconds %= 86400;
      int hours = seconds / 3600;
      seconds %= 3600;
      int minutes = seconds / 60;
      seconds %= 60;

      if (days > 3650) {
        return {"Starting up"};
      } else if (days > 0) {
        return {str_sprintf("%dd %dh %dm %ds", days, hours, minutes, seconds)};
      } else if (hours > 0) {
        return {str_sprintf("%dh %dm %ds", hours, minutes, seconds)};
      } else if (minutes > 0) {
        return {str_sprintf("%dm %ds", minutes, seconds)};
      } else {
        return {str_sprintf("%ds", seconds)};
      }
    icon: mdi:clock-start

#Button Configurations
#Device Physical Button
binary_sensor:
  - platform: gpio
    pin:
      number: PA22
      mode: INPUT_PULLUP
      inverted: true
    id: "relay_button"
    name: "Power Button"
    disabled_by_default: true
    filters:
      - delayed_on: 50ms
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - switch.toggle: relay
      - timing:
          - ON for at least 10s  # Long press for reset
        then:
          - button.press: device_reset
    
#Factory Reset "Soft-Button"
button:
  - platform: factory_reset
    id: "device_reset"
    name: "Reset to Factory Default Settings"
    entity_category: diagnostic
#Device Restart "Soft-Button"
  - platform: restart
    name: "Restart"
    id: "device_restart"
    entity_category: diagnostic
#Safe Mode "Soft-Button"
  - platform: safe_mode
    name: "Safe Mode"
    id: "device_safe_mode"
    internal: false
    entity_category: config


time:
  - platform: sntp
    id: sntp_time
  # Define the timezone of the device
    timezone: "${timezone}"
  # Change sync interval from default 5min to 6 hours (or as set in substitutions)
    update_interval: ${sntp_update_interval}
  # Set specific sntp servers to use
    servers: 
      - "${sntp_server_1}"
      - "${sntp_server_2}"
      - "${sntp_server_3}"    
  # Publish the time the device was last restarted
    on_time_sync:
      then:
        # Update last restart time, but only once.
        - if:
            condition:
              lambda: 'return id(device_last_restart).state == "";'
            then:
              - text_sensor.template.publish:
                  id: device_last_restart
                  state: !lambda 'return id(sntp_time).now().strftime("%a %d %b %Y - %I:%M:%S %p");'